### ISSUE TITLE
Jump UI helpers appear when I trigger CodeFlea: Jump but subsequent key presses do nothing

### ISSUE THREAD

**Issue by devCronos** [Richiban/CodeFlea#11]
Hello guys. The extension looks awesomely useful to me. I just installed it and can't seem to get it to work.
Jump when triggered makes the jump points appear but subsequent key presses don't work; nor does escape to get rid of the ui.
The cursor jump is not made and I'm just typing characters.

Also alt+keys just types special characters. Should I disable this feature on my macos machine ?
How was this intended to be used ?

**Comment by Richiban** [comment]
Hi @devCronos, the `ALT` codes problem definitely sounds like a platform issue; I haven't got a Mac so I wasn't aware of the effect the ALT key would have. My suggestion here would be to simply rebind the default shortcuts to something else of your choosing. The commands themselves should still work.

As for the issue where the jump codes are appearing but pressing a key does nothing; that's a new one to me. I've not heard any reports of that before, is it possible that another extension you have is stealing input, e.g. something like a Vim emulator? If you don't mind I'd appreciate it if you could run a test for me by disabling all other extensions and seeing if CodeFlea runs on its own. That will tell us if extension clash is the issue.

**Comment by devCronos** [comment]
Hello there. The not jumping problem fixed by itself when I restarted vscode. I don't know why I didn't try that before asking here. Will disable my default alt functionality. I like your default keybindings.  Thanks for your work man. Beautiful idea with this extension

**Comment by Richiban** [comment]
Glad to hear that you like it! Let me know if you have any problems or find any bugs; filing a GitHub issue would be appreciated.
