### ISSUE TITLE
Command not working

### ISSUE THREAD

**Issue by thiagomajesk** [Richiban/CodeFlea#7]
Just installed this extension with the latest vscode release and the command to open simply does nothing...
Do I have to manually bind to some command, if yes, what's the command to fire up the jump locations?

Also, I've noticed that the commands listed here: https://github.com/Richiban/CodeFlea#commands are not "namespaced", which makes it harder to find in the palette, I suggest updating the command names with the extension name, like: `CodeFlea: nextInterestingLine`, for example.

**Comment by Richiban** [comment]
Thanks for your suggestions Thiago, I'll get those changes made as soon as possible.

It's possible the main jump command has not been given a keybinding for you; you can try searching for `codeFlea.jump` in your list of keybindings or make a new one if it's absent.

Please let me know if you have any more issues.

**Comment by Richiban** [comment]
In the latest release v0.9 the commands have all been namespaced so they're much easier to find in the command palette
